### ISSUE TITLE
ContainerPilot and repo org cleanup

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#13]
- Confirm the SHA fingerprint when installing ContainerPilot
- Copy this repo's `bin` to `/usr/local/bin` instead of just `/bin`
- Move config items (`config/consul.json and`containerpilot.json`) to`etc` in this repo

**Comment by mterron** [comment]
Could you add a checksum file next to the CP release in addition to the line in the release comment? That way checksum checking could be automated (see mterron/consul-autopilot/ Dockerfile)

**Comment by tgross** [comment]
Done in https://github.com/autopilotpattern/consul/pull/19
