### ISSUE TITLE
Consul will fail to start up when multiple RFC1918 IPs are attached to the instance

### ISSUE THREAD

**Issue by dekobon** [autopilotpattern/consul#17]
For example, if you are running Consul in a network with multiple private IPs associated with NICs on the Consul instance, when Consul boots up, it will be unable to auto-select the network it should advertise on.

When using Consul on multiple private networks without Docker, this is a simple fix - you just specify the IP of the private network that you want to advertise on. However, when you use Docker, specifying the IP as part of the startup parameters gets you into a chicken and egg problem.

Ideally, ContainerPilot could support templating in the available IPs into the run command executed.

**Comment by tgross** [comment]
I'm reworking this blueprint to use CNS and I'll adapt it to include the use of the `CONTAINERPILOT_[SERVICE]_IP` env var that we exposed in https://github.com/joyent/containerpilot/issues/145 and https://github.com/joyent/containerpilot/issues/171
