### ISSUE TITLE
Build Consul based on Musl

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#2]
From https://github.com/misterbisson/triton-consul/pull/1#discussion_r43030068

To eliminate the need to download a glibc from the internets, this project should build a version of Consul based on Musl. How to do this in a way that minimizes [the harm of `go get](http://0x74696d.com/posts/go-get-considered-harmful/) and in a separate build container to eliminate the unneeded bulk from the Golang build environment.

**Comment by misterbisson** [comment]
From @tgross in https://github.com/misterbisson/triton-consul/pull/1#discussion_r43031679:

> It occurs to me that a musl build for something running DNS is something we'd want to test out quite a bit. One of the big behavioral differences between musl and libc is the DNS client library. Not sure if that'll turn out to be relevant for a Go program, but worth checking.

**Comment by ddunkin** [comment]
This isn't required for Consul 0.6 because it is all Go.

As for DNS, Go uses a [pure Go DNS resolver by default](https://golang.org/pkg/net/#hdr-Name_Resolution) on UNIX systems.

**Comment by misterbisson** [comment]
Yes, the ticket description was based on a misunderstanding of the glibc dependency. It's fixed now, thanks to your PR: https://github.com/autopilotpattern/consul/pull/10.
