### ISSUE TITLE
Nodes failing to join

### ISSUE THREAD

**Issue by jmheidly** [autopilotpattern/consul#20]
I tried running ./start.sh which spawned 3 consul instances each trying to join the other but failing to do so. Here is a log dump for you reference.

Successfully joined cluster by contacting 1 nodes.
    2016/06/23 17:33:59 [ERR] agent: failed to sync changes: No cluster leader
    2016/06/23 17:33:59 [ERR] agent: failed to sync remote state: No cluster leader
    2016/06/23 17:34:08 [INFO] agent.rpc: Accepted client: 127.0.0.1:62022
    2016-06-23 17:34:08 containerpilot: No peers in raft
    2016-06-23 17:34:08 containerpilot: Bootstrapping raft with self
    2016/06/23 17:34:09 [INFO] agent.rpc: Accepted client: 127.0.0.1:61514
    2016/06/23 17:34:09 [INFO] agent: (LAN) joining: [192.168.128.18]
    2016/06/23 17:34:09 [INFO] agent: (LAN) joined: 1 Err: <nil>
Successfully joined cluster by contacting 1 nodes.
    2016/06/23 17:34:09 [ERR] agent: failed to sync changes: No cluster leader
    2016/06/23 17:34:14 [ERR] agent: coordinate update error: No cluster leader

What could be causing the issue?

**Comment by tgross** [comment]
This should be solved by https://github.com/autopilotpattern/consul/pull/19
