### ISSUE TITLE
Clean up Docker Hub tags

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#21]
https://hub.docker.com/r/autopilotpattern/consul/tags/ shows some tags we can't account for, specifically, tags that don't have a release version in https://github.com/autopilotpattern/consul/releases. Further, the tag pattern doesn't identify what version of Consul is present in the container.
1. Going forward we'll tag releases with `<consul version>-r<implementation version>`, a pattern that's used in other Autopilot Pattern implementations
2. Every tagged version in Docker Hub must have a matching version in https://github.com/autopilotpattern/consul/releases
3. On 8 July we'll remove all non-conforming tags from https://hub.docker.com/r/autopilotpattern/consul/tags

**Comment by tgross** [comment]
@misterbisson all remaining tags on Docker Hub that don't have corresponding releases have been deleted. This leaves the `0.4` and `0.3` tags on the Docker Hub which don't conform to the naming guidelines but do have an associated release in GitHub. I think we can close this?
