### ISSUE TITLE
Add data center name in Config file

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#23]
Consul's has built-in support for operation in multiple data centers. These data centers can be named.

The data center name can be set in the [`consul.json`](https://github.com/autopilotpattern/consul/blob/master/etc/consul.json) with the addition of a `"datacenter": "<name>"` key, *_or_ with the addition of a [`-datacenter` command line argument](https://www.consul.io/docs/agent/options.html#_datacenter). 

The Triton data center name can be found using [`mdata-get`](http://eng.joyent.com/mdata/datadict.html):

``` bash
/native/usr/sbin/mdata-get sdc:datacenter_name
```

The name can be injected in the config file at `preStart` using [a mechanism similar to how the advertise IP is set](https://github.com/autopilotpattern/consul/blob/master/bin/consul-manage#L8):

``` bash
if [ -f "/native/usr/sbin/mdata-get" ]; then
  DATACENTER_NAME=$(/native/usr/sbin/mdata-get sdc:datacenter_name)
fi
sed -i "s/DATACENTER_NAME/${DATACENTER_NAME:-dc1}/" /etc/consul/consul.json
```

**Comment by jwreagor** [comment]
Interesting, I like the usage of metadata. I can add this into the mix after #43 is merged.
