### ISSUE TITLE
Add support for encrypted LAN and WAN gossip

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#24]
https://www.consul.io/docs/agent/encryption.html describes enabling encryption for gossip communications in the LAN and over the WAN:

> gossip between nodes is done over UDP and is secured using a symmetric key

The key is 16-bytes, Base64 encoded.

The included `consul keygen` command can create a suitable key (example: `cg8StVXbQJ0gPvMd9o7yrg==`), but that key must be distributed to _every_ Consul instance. For this to work, the key must be generated outside the instance and provided at the time the containers are scheduled.

If this key is provided via an optional environment var, it could be injected in the [`consul.json`](https://github.com/autopilotpattern/consul/blob/master/etc/consul.json) config file at `preStart` using [a mechanism similar to how the advertise IP is set](https://github.com/autopilotpattern/consul/blob/master/bin/consul-manage#L8):

``` bash
if [ ! -z "$CONSUL_GOSSIP_KEY" ]; then
  sed -i "s/\{/\[\n\"encrypt\": \"${CONSUL_GOSSIP_KEY},\"/" /etc/consul/consul.json
fi
```

As a practical matter, alternatives to `consul keygen` will likely be needed to make it easy to inject the key into environment variable configuration for the application (see example in [autopilotpattern/wordpress](https://github.com/autopilotpattern/wordpress/blob/master/setup.sh#L114)).

**Comment by tgross** [comment]
> As a practical matter, alternatives to consul keygen will likely be needed to make it easy to inject the key into environment variable configuration for the application

Alternately, this would be a good use case for a combined Vault-Consul container instance.

**Comment by misterbisson** [comment]
> this would be a good use case for a combined Vault-Consul container instance

Expanding that a bit, correct me if I'm wrong:

We can't use Consul to discover Vault, but by combining Vault on the same instances as the Consul raft instances, we can _assume_ that Vault is reachable using the same DNS name we use for Consul.

That could work. Getting the Consul key from Vault in the `preStart` hook would be possible. However, generating that key and seeding it in Vault may not be possible automatically (because we can't use Consul for consensus about who the leader is for that transaction).

It might be possible to start the Consul raft without encryption, have it negotiate and distribute the key, then restart in encrypted mode. This would require that each Consul instance check Vault for a key at startup. If no key exists, it would generate the key (risking a partition, and requiring some work to make sure it doesn't connect to its own Vault). Consul co-process agents in other containers would need to go through the same `preStart` process to fetch the key from Vault. 

---

My feeling is that the easiest solution is probably to generate the encryption key in the user environment (laptop, wherever) and include it with any other configuration environment vars the user may set.

**Comment by tgross** [comment]
> That could work. Getting the Consul key from Vault in the preStart hook would be possible. However, generating that key and seeding it in Vault may not be possible automatically 

Yeah the important thing to realize here is that you need a mechanism for secure injection of the "first secret". . The workflow for Vault and containers is:
- The Vault needs to be "unsealed" after deployment (typically w/ multiple keys split via Shamir secret splitting)
- For each container you want to launch, you (or your scheduler) get a one-time-use token from Vault that grants access to the renewable token for that role.
- Each container that needs a secret is launched with that one-time-use token (as an env var). During `preStart` the container uses this token to fetch its renewable token from Vault.
- The container then uses this token to get the certs, secrets, etc. its been granted.

This is leading me to think that combining Vault and Consul might not actually be a good idea, and that the Compose workflow we've been using doesn't work with Vault either. You really want a scheduler in the mix here because of the need for the one-time-use token.

**Comment by misterbisson** [comment]
> really want a scheduler in the mix here

Well, a more sophisticated scheduler than we've demonstrated, anyway ;-)

For the purpose of exploring the problem, I'm happy to leave Vault and other more sophisticated approaches to secret management out of scope.

**Comment by tgross** [comment]
This is demonstrated in the [Vault blueprint](https://github.com/autopilotpattern/vault#encrypted-communications). Do we want to maybe have a section of the README that directs users there?

**Comment by tgross** [comment]
Added to README in https://github.com/autopilotpattern/consul/pull/32
