### ISSUE TITLE
Add support for custom RPC encryption with TLS 

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#25]
This [early 2015 mail list item addresses the question of how to secure Consul for use over a WAN](https://groups.google.com/forum/#!topic/consul-tool/oi4fCTqR-C0):

> Security on public addresses: Consul can be run securely over the WAN if you enable all the encryption features. This means `-encrypt` for gossip, and the TLS settings with `verify_incoming` and `verify_outgoing`. See this page: https://consul.io/docs/agent/encryption.html

https://github.com/autopilotpattern/consul/issues/24 addresses adding support for gossip encryption, this ticket addresses TLS.

[From the docs](https://www.consul.io/docs/agent/encryption.html):

> If `verify_outgoing` is set, agents verify the authenticity of Consul for outgoing connections. Server nodes must present a certificate signed by the certificate authority present on all agents, set via the agent's `ca_file` option. All server nodes must have an appropriate key pair set using `cert_file` and `key_file`.
> 
> If `verify_incoming` is set, the servers verify the authenticity of all incoming connections. All clients must have a valid key pair set using `cert_file` and `key_file`. Servers will also disallow any non-TLS connections. To force clients to use TLS, `verify_outgoing` must also be set.

The configuration options seem simple enough, but further work must be done to define a workflow in which this can be used and operated automatically. It's possible that ~~this can use Let's Encrypt to generate keys automatically (also see https://github.com/autopilotpattern/nginx/issues/25), or that~~ the keys can be completely optional and provided in the environment configuration as described in https://github.com/autopilotpattern/consul/issues/24 (edit: we can't coordinate Let's Encrypt without having Consul working, so any keys must be provided to the scheduler for this to work, rather than generated at run-time).

**Comment by tgross** [comment]
This is demonstrated in the [Vault blueprint](https://github.com/autopilotpattern/vault#encrypted-communications). Do we want to maybe have a section of the README that directs users there?

**Comment by tgross** [comment]
Added to README in https://github.com/autopilotpattern/consul/pull/32
