### ISSUE TITLE
Update to Consul 1.0.0

### ISSUE THREAD

**Issue by tgross** [autopilotpattern/consul#36]

**Comment by mechastorm** [comment]
Just wanted to know what are the main challenges in updating this codebase to support the latest version of Consul (0.8.x)?

**Comment by misterbisson** [comment]
@mechastorm there are no technical issues blocking this. Our attention has been focused on ContainerPilot 3 (there's a PR open in https://github.com/autopilotpattern/consul/pull/37 with those changes). Our attention has further been focused on improving the testing we do to these application blueprints (see that work progressing in https://github.com/autopilotpattern/nginx/pull/52).

Additionally, Consul 0.8 had some reliability issues in the first few versions, so we've been waiting for those to work out.

I should clarify, however, that the [new Consul 0.8 feature named "autopilot"](https://www.consul.io/docs/guides/autopilot.html) is unrelated to ContainerPilot and the Autopilot Pattern. It's really unfortunately that Hashicorp chose a name that creates market confusion. It's also unfortunate that most of the benefits of Consul's new Autopilot mode are available only to users with commercial Enterprise support contracts.

**Comment by jwreagor** [comment]
I bumped this title to 1.0.0 since 0.8 is way old now.

**Comment by jacobloveless** [comment]
One note the `recursor` key in the consul.json (pre 1.0.0)  is now `recursors` and expects an array. 
e.g. 
```  "recursors":["8.8.8.8","8.8.4.4"],```  

[consul 1.0.0 ref](https://www.consul.io/docs/agent/options.html#recursors)

**Comment by jwreagor** [comment]
Thanks Jacob! I've got that included in my open PR, #43. I didn't have a proper link setup to mention this issue, apologies for that.

While there wasn't much in the way of changes to satisfy the upgrade, #43 includes the first release of ContainerPilot (3.6.0) which explicitly targets the 1.x release cycle. ContainerPilot is now built with the latest Consul APIs as well as running integration tests against 1.x moving forward.

**Comment by jwreagor** [comment]
Actually, I just realized I didn't add the second DNS server under `recursors`. I'll push that into my PR tomorrow.

**Comment by jacobloveless** [comment]
I think the consul health check is more like this in Consul 1.0.0 ? 
```
consul_health() {
    if [ $(consul info | awk '/members/{print$3}') == 0 ]; then
        _log "No peers in raft"
        consul join ${CONSUL}
    fi
}
```
 https://github.com/autopilotpattern/consul/blob/master/bin/consul-manage#L18

**Comment by jacobloveless** [comment]
Also I think maybe we should start making these examples (e.g. README.md) explicit about the fact they are not CP3 compatible yet.

**Comment by jwreagor** [comment]
The `README.md` is definitely out of sync and that's a glaring omission on my part. I'll get a new PR out ~~some time tomorrow~~.

**Comment by jwreagor** [comment]
Actually this `README.md` has been in play since before my PR but I'm not pointing fingers. 😬
