### ISSUE TITLE
Question: what does `preStop` mean when used as a source?

### ISSUE THREAD

**Issue by sungwonh** [autopilotpattern/consul#40]
https://github.com/autopilotpattern/consul/blob/master/etc/containerpilot.json5#L33

in the configuration above,
`preStop` is used as a source, but it is not defined as a job in the configuration. Could anyone let me know what `preStop` means in the configuration file?

**Comment by tgross** [comment]
That's a configuration bug @sungwonh. The source should be `consul` for the `preStop` job. Thanks for catching that, and I'll open a PR to fix later this morning.

**Comment by sungwonh** [comment]
Thank you for your answer!
