### ISSUE TITLE
Health check on the agent needs to be a bit more robust

### ISSUE THREAD

**Issue by jwreagor** [autopilotpattern/consul#45]
@jacobloveless writes...

> I think the health check on the agent needs to be a bit more robust. If I read this correctly, this will mark the agent as healthy even if it isn't yet in sync on raft which might cause issues. Perhaps something like...

```bash
  if [ $(consul info | awk '/members/{print$3}') == 1 ]; then
       _log "No peers in raft"
       consul join ${CONSUL}
  fi
```

The documentation for the existing Consul server health check matched the behavior when I investigated previous versions. Here's the existing check and documentation for note...

```bash
#
# Check if a member of a raft. If consul info returns an error we'll pipefail
# and exit for a failed health check.
#
# If we have no peers then try to join the raft via the CNS svc record.  Once a
# node is connected to at least one other peer it'll get the rest of the raft
# via the Consul LAN gossip.
#
# If we end up joining ourselves we just retry on the next health check until
# we've got the whole cluster together.
#
health() {
    if [ $(consul info | awk '/num_peers/{print$3}') == 0 ]; then
        _log "No peers in raft"
        consul join ${CONSUL}
    fi
}
```

**Comment by jwreagor** [comment]
After looking at the lifecycle I'm not seeing a case where `raft.num_peers == 1` before any member has formed a cluster via `consul join`. We always want a new `consul agent -server` to join the cluster if it is unaware of any members previously. Also, someone could run a single Consul server and the health of an instance prior to joining a cluster should be green.

Thoughts?

**Comment by jacobloveless** [comment]
To me it wasn't understood that raft.num_peers reflects a functional
cluster initially so maybe just add a comment here to linking to the consul
docs?

Something like:
Note:
For our consul server cluster, to verify that the cluster is successfully
bootstrapped and ready.
Consul's raft.num_peers variable will be set to value >=1 once the Consul
servers are bootstrapped. See  https://www.consul.io/docs/gui
des/bootstrapping.html#verifying-the-cluster for more details

**Comment by jwreagor** [comment]
Sounds good. I just wanted to make sure I didn't miss something else in the upgrade. I'll add that documentation piece to the open PR.

**Comment by jacobloveless** [comment]
Might also be nice to have an example of the consul-agent in this repo as
well ... since these are the two main components we need to get going?

**Comment by jwreagor** [comment]
Here's [a link to the new `README.md`](https://github.com/autopilotpattern/consul/blob/4f8e507244fd21d4981d4257f4df5095ba028a54/README.md#using-this-in-your-own-composition) which has the `consul-agent` as the example.

**Comment by jacobloveless** [comment]
So what I think I was trying to say (but wasn't clear at all) is this:

A new user will likely come here after a basic hello world example.
This repo (and README) works great for the consul-server but if I simply
take the example consul-agent here and the consul.hcl and Dockerfile from
this repo I would get tripped up because our `consul.hcl` expects
`CONTAINERPILOT_CONSUL_IP`
which won't exist in the agent image.

https://github.com/autopilotpattern/consul/blob/master/etc/consul.hcl#L1

Perhaps the change is to
https://github.com/autopilotpattern/consul/blob/master/bin/consul-manage#L10
and we switch between CONTAINERPILOT_CONSUL_IP (if it exists) and default
to CONTAINERPILOT_CONSUL_AGENT_IP?

**Comment by jwreagor** [comment]
Ignore what this project is doing for running Consul within your own containers and only use this pattern for when you need to run a Consul cluster itself.

If you're running a `consul-agent` job ([like this](https://github.com/autopilotpattern/nodejs-example/blob/master/frontend/containerpilot.json5#L20)) you only need to [give consul the address](https://github.com/autopilotpattern/nodejs-example/blob/master/frontend/containerpilot.json5#L26) of an external Consul cluster member. You won't need an env var or config file since you'll only be binding this consul process to localhost for serving internal container traffic ([like containerpilot](https://github.com/autopilotpattern/nodejs-example/blob/master/frontend/containerpilot.json5#L2)) from within the container itself.

This is what I need to tighten up in the documentation for this project. Generally every pattern handles the consul agent this way, at least those running ContainerPilot v3.
