### ISSUE TITLE
Cleanup services when TTL expired

### ISSUE THREAD

**Issue by j0hnsmith** [autopilotpattern/consul#6]
Once the TTL for a service has expired, is there any expectation that the service will come back with Triton (scaled down: no, service updated: no, hardware failure: maybe, os update: yes)?

Would it make sense for a cleanup process to exist within this container (once a service has been down say 30 mins or whatever)?

https://github.com/hashicorp/consul/issues/679

**Comment by misterbisson** [comment]
@j0hnsmith: I think you're right to link to https://github.com/hashicorp/consul/issues/679, as it's definitely a question that affects Consul generally.

My use is typically via http://containerbuddy.io, which will now deregister services when the container is stopped, thanks to https://github.com/joyent/containerbuddy/pull/22.

**Comment by j0hnsmith** [comment]
I am using containerbuddy with that feature but I was using `docker kill` to see what would happen, the discussion in that pull covers the different stop/kill containerbuddy behaviours.
