### ISSUE TITLE
consul fails to elect leader

### ISSUE THREAD

**Issue by ghost** [autopilotpattern/consul#8]
This is likely not an issue with this code but I sometimes have a situation where the consul raft fails to elect a leader so writing the nginx template loop never succeeds. This seems to most often happen in the  Amsterdam datacenter. Do you have any idea what would cause this. I understand that it can take a while to elect the leader but I have let it run as long as 5 minutes with no success. This does not always occur but it does fairly regularly in ams.

**Comment by misterbisson** [comment]
@donniev what do the logs show? Do all three instances have connectivity to each of the other two?

**Comment by ghost** [comment]
Here are the logs.  This was created by running the example in ams zone so it is using old containerbuddy.

http://pastebin.com/fPXLmSME

It does not fail every time.

**Comment by misterbisson** [comment]
What about the output of `start.sh` when starting up?

**Comment by misterbisson** [comment]
...and the question of connectivity among all three hosts?

**Comment by ghost** [comment]
I don't know how to check the connectivity. That would be a joyent issue correct? All I do is run start.sh

http://pastebin.com/4SgSkCbi

**Comment by ghost** [comment]
If I shell into consul_1 and ping the external ip's of consul_2 and 3 it succeeds.

**Comment by misterbisson** [comment]
> If I shell into consul_1 and ping the external ip's of consul_2 and 3 it succeeds.

Please also check the internal IPs, and confirm the same for consul_2 and 3?

Also, please `echo $BOOTSTRAP_HOST` on your laptop just after attempting to start the raft, and each of the three containers? I'd like to confirm that it's set everywhere (except on consul_1, which should be the bootstrap host). On your laptop, this is set via https://github.com/misterbisson/triton-consul/blob/master/start.sh#L36 and then passed in to instances 2 and 3 when the `start.sh` script does the `docker compose scale...` via https://github.com/misterbisson/triton-consul/blob/master/docker-compose.yml#L21-L22 .

**Comment by ghost** [comment]
For whatever reason the BOOTSTRAP_HOST is set to empty when it fails:
I replaced that line with

```
export BOOTSTRAP_HOST="$(triton inst get ${APPPREFIX}_consul_1 | json -a ips.0)"
```

which works (I did this in real project I am working on which uses APPPREFIX )

I realize this couples code to triton instead of using just a docker command but for today a workaround is all I have time for.

**Comment by misterbisson** [comment]
As long as your `triton` profile is pointing to the same DC as your `docker` env, that should work.

**Comment by misterbisson** [comment]
We've implemented checking in scripts for other repos that will confirm that `triton` and `docker` are both configured to use the same data center. See https://github.com/autopilotpattern/couchbase/blob/master/setup.sh#L32-L108

We'll implement a similar solution here. Closing this one now, though.
